include:
  - project: "spacex/ci-templates"
    file: "deno.gitlab-ci.yml"
    # ref: "dev"

variables:
  CI_DOCKER_PROJECT: xx
  CI_DOCKER_REPO: xx-server    
  CI_UPGRADE_HOSTNAME: xx.com
# CI_STATIC_SCAN: "true" # 开启静态文件扫描
  CI_ENABLE_TEST: "true" # 开启单元测试
  CI_ENABLE_MANUAL_UPGRADE: "true" # 开启手动升级
