port: 3000
apiPrefix: api
db: 'mongodb://10.100.30.65:27018/test'
ssoApi: "https://sso.3dlink.cn/api/"
log:
  appenders:
    dateFile:
      filename: logs/deno
      daysToKeep: 10
      pattern: yyyy-MM-dd.log
  categories:
    default:
      appenders:
        - dateFile
        - console
      level: DEBUG
