# docker-compose build 或 up
version: '3'
services:
  auth:
    # image: dk.uino.cn/kiss/auth-server:master
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
       - "3000:3000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config/server.yaml:/app/config/server.yaml
